In [12]:
import pandas as pd
import matplotlib
from sklearn import preprocessing
%matplotlib inline

In [13]:
df = pd.read_csv(r'C:\Users\dakar\Desktop\NFL\NFL.csv', low_memory=False)

In [14]:
#filter columns
nedf = df[['posteam','qtr','score_differential','game_seconds_remaining', 'yardline_100', 'down', 'ydstogo', 'play_type', 'pass_length', 'pass_location', 'run_location']]

In [15]:
nedf

,posteam,qtr,score_differential,game_seconds_remaining,yardline_100,down,ydstogo,play_type,pass_length,pass_location,run_location
0,PIT,1,NaN,3600.0,30.0,NaN,0,kickoff,NaN,NaN,NaN
1,PIT,1,0.0,3593.0,58.0,1.0,10,pass,short,left,NaN
2,PIT,1,0.0,3556.0,53.0,2.0,5,run,NaN,NaN,right
3,PIT,1,0.0,3515.0,56.0,3.0,8,pass,deep,right,NaN
4,PIT,1,0.0,3507.0,56.0,4.0,8,punt,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
449366,CAR,4,-5.0,63.0,66.0,2.0,10,pass,short,middle,NaN
449367,CAR,4,-5.0,58.0,66.0,3.0,10,pass,short,middle,NaN
449368,CAR,4,-5.0,38.0,61.0,4.0,5,pass,short,right,NaN
449369,NO,4,5.0,35.0,39.0,1.0,10,qb_kneel,NaN,NaN,NaN
449370,NaN,4,NaN,0.0,NaN,NaN,0,NaN,NaN,NaN,NaN

In [16]:
nedf.to_csv (r'C:\Users\dakar\Desktop\Finalpj\raw2.csv', index = False, header=True)